



remote_theme: pmarsceill/just-the-docs



title:  Synthetic control methods
description: Follow the latest developments in the SC literature.
#baseurl: "/SC" # the subpath of your site, e.g. /blog
#url: "https://wenddymacro.github.io/SC/" # the base hostname & protocol for your site, e.g. http://example.com

logo: "/image/IMG_3695.JPG"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer content
footer_content: "Content by Wenli Wenddy Xu (2022-2022). Distributed under an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true 
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: false # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/wenddymacro/SC" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Change to dark mode here: color_scheme: dark

permalink: pretty
exclude: ["README.md", "Gemfile"]
include: ["docs"]


# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "https://wenddymacro.github.io/SC/" 
    
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

nav_sort: case_sensitive # Capital letters sorted before lowercase


# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Plug-ins
plugins:
  - jekyll-seo-tag



compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all


usemathjax: true

compress_html:
  blanklines: true # needed to render Mathjax correctly

#layout: default
#title: UI Components
#nav_order: 2
#has_children: true
#has_toc: false


mathjax:
  source: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS_CHTML
  config: 'MathJax.Hub.Config({ TeX: { equationNumbers: { autoNumber: "AMS" } } })'
© 2022 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
